### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by danleyb2**

### CODE REVIEW

**Comment by danleyb2** [comment]
@marcbelmont 
I am not sure we should merge this.
There are actual bugs fixed but i had to also downgrade gradle for the build to work on my AndroidStudio version.

**Comment by marcbelmont** [comment]
@danleyb2 any ideas why the downgrade was needed? Did you get any error messages?

The current version is broken. Your changes will be an improvement over that.

**Comment by danleyb2** [comment]
@marcbelmont Yes. Had created this PR to share fixes to a customer. 
I need to upgrade AndroidStudio  higher than V3 to be able to build with the original gradle version. 
Let's wait for when i am able to test  with the higher version

**Comment by danleyb2** [comment]
@marcbelmont Have confirmed the APP works okay without the downgrade. Kindly review

**Review by marcbelmont — APPROVED** [review]

**Pull request merged**
